# Generated by Django 5.2.10 on 2026-01-14 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JsonPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial success', 'Partial Success'), ('fail', 'Fail')], max_length=25)),
                ('error', models.TextField(null=True)),
                ('payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payload', to='app.jsonpayload')),
            ],
        ),
        migrations.CreateModel(
            name='ImageArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], max_length=25)),
                ('filename', models.TextField()),
                ('base64_data', models.BinaryField(null=True)),
                ('file_path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path', to='app.filepath')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.request')),
            ],
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['timestamp'], name='app_request_timesta_9fe4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['user_ip'], name='app_request_user_ip_18d097_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='app_request_status_e9eeb7_idx'),
        ),
    ]
