# Generated by Django 5.2.10 on 2026-01-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_imageartifact_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageartifact',
            name='base64_data',
            field=models.TextField(null=True),
        ),
    ]
